from nicegui import app, ui

LANGUAGES = {
    'zh-TW': {
        'create_session': '正在創建新會話...',
        'version_history': '版本歷史',
        'download_application': '下載應用',
        'new_application': '新製作',
        'new_app': '新增應用',
        'app_store': '社區應用',
        'application_filename': '應用-{id}.url',
        'ai_suggestion': 'AI生成結果未如理想時，建議直接使用上方按鈕回到之前的版本重新提出需求。',
        'conversation': '對話',
        'input_placeholder': '請描述您想要的工具...',
        'send': '發送',
        'stop': '停止',
        'tool_preview': '工具預覽',
        'edit_code': '修改程式碼',
        'publish_app': '發佈為應用',
        'generate_new_template': '為我生成新的應用模版',
        'manage_publish': '管理發佈',
        'dedicated_page': '獨立頁面',
        'edit_code_manually': '手動修改程式碼',
        'cancel': '取消',
        'save_changes': '保存修改',
        'publish': '提交審核', # Changed from '發佈'
        'unpublish': '下架封存', # Changed from '下架'
        'app_name_label': '應用名稱',
        'publish_dialog_title': '發佈應用',
        'app_published_success': '應用「{name}」已成功提交審核！',
        'app_unpublished_success': '應用已成功下架封存。',
        'confirm_cancel_submission_text': '您確定要取消對應用 {name} 的審核提交嗎？',
        'confirm_go_live_text': '您確定要將已批准的應用 {name} 正式發佈上線嗎？',
        'confirm_unpublish_text': '您確定要將已發佈的應用 {name} 下架封存嗎？',
        'app_updated_success': '應用已更新為版本 V{v_num}。',
        'use_app': '使用應用',
        'published_mark': '（已發佈）',
        'chat_you': '您',
        'chat_ai': 'AI',
        'chat_system': '系統',
        'ai_thinking': 'AI 正在思考中...',
        'ai_settings_incomplete': 'AI 設定不完整或不正確。',
        'go_to_management_for_config': '<br>請點擊<a href="/management" style="text-decoration: underline; color: #3B82F6;">此處</a>前往管理中心進行設定。',
        'system_prompt_not_found': '系統提示未找到。',
        'ai_no_html': 'AI 未能生成有效的 HTML 內容。',
        'api_request_failed': '<b>API 請求失敗</b>',
        'cannot_connect_ai': '<b>無法連接到 AI 伺服器</b>',
        'unexpected_error': '<b>發生未預期的錯誤</b>:',
        'error_notification': '發生錯誤: {e}',
        'ai_busy_or_no_response': 'AI 服務繁忙或無回應',
        'based_on_v': '基於 V{v_num}',
        'preview_title': '版本 V{v_num}{base_text}',
        'based_on_v_suffix': ' (基於 V{v_num})',
        'code_saved_as_v': '程式碼已手動修改並保存為 V{v_num}。',
        'generated_v': '已為您生成 V{v_num}。',
        'request_changes_for_v': '請提出對版本 V{v_num} 的修改...',
        'cannot_save_no_base': '無法保存，沒有基礎版本或內容為空。',
        'saving_changes': '正在保存修改...',
        'manual_edit_request': '手動修改',
        'no_history': '無歷史紀錄。',
        'user_request_history': '使用者 (V{v_num} 的需求): {request}',
        'window_title': 'Vibe coding DEMO',
        'lang_button': '繁/EN',
        'app_description_placeholder': '這是一個很棒的應用程式，可以幫助您完成很多事情。',
        'version_not_found': '找不到指定的應用程式版本',
        'share_not_found_or_expired': '分享的應用程式不存在或已過期',
        'user_login': '使用者登入',
        'username': '使用者名稱',
        'password': '密碼',
        'login': '登入',
        'logout': '登出',
        'login_error': '帳號或密碼錯誤',
        'my_apps': '我的',
        'latest_apps': '最新發佈的應用',
        'no_apps_in_store': '商城還沒有任何應用。',
        'no_preview_available': '無可用預覽',
        'preview_generation_failed': '預覽生成失敗',
        'generating_preview': '正在生成預覽...',
        'manage': '管理',
        'you_have_no_apps': '您還沒有任何應用。',
        'my_shares': '我的分享',
        'app_name': '應用名稱',
        'share_link': '分享連結',
        'expires_at': '到期時間',
        'actions': '操作',
        'permanent': '永久',
        'share_link_removed': '分享連結已移除。',
        'remove_share': '移除分享',
        'copy_link': '複製連結',
        'link_copied': '連結已複製到剪貼簿！',
        'you_have_no_shares': '您沒有任何分享。',
        'confirm_delete_app_title': '您確定要刪除這個應用嗎？此操作無法復原。',
        'app_deleted': '應用已刪除。',
        'confirm_delete': '確定刪除',
        'close': '關閉',
        'share': '分享',
        'delete_app': '刪除應用',
        'share_app_version': '分享應用版本',
        '1_day': '1 天',
        '7_days': '7 天',
        '1_month': '1 個月',
        'share_duration': '分享時長',
        'cannot_generate_share_link': '無法生成分享連結。',
        'generate_link': '生成連結',
        'share_link_generated': '分享連結已生成並複製到剪貼簿！',
        'processing_request': '正在處理請求，請稍候...',
        'under_review': '管理審核中',
        'go_live': '正式發佈',
        'manage_published_version': '管理已發佈版本',
        'preview_generating': '預覽生成中...',
        'managing_review_app': '管理審核中的應用',
        'app_approved': '應用已批准',
        'cancel_submission': '取消提交',
        'submission_cancelled': '已取消提交審核。',
        'app_live_success': '應用已成功發佈上線！',
        'app_name_required': '請輸入應用名稱',
        'app_description_required': '請輸入應用描述',
        'user_info_error': '錯誤：找不到使用者資訊，請重新登入。',
        'app_submitted_for_review': '應用已提交審核，預覽圖將在後台生成。',
        'publish_failed': '發佈失敗: {e}',
        'manual_edit_by_user': '用戶手動修改了程式碼。',
        'welcome_message': '歡迎使用！請開始您的第一個需求',
        'archive_before_delete': '刪除應用前，請先將其「下架封存」。',
        'preview_worker_started': '預覽生成後台工作線程已啟動。',
        'template_generation_failed': 'AI未能生成有效的預覽模板。',
        'preview_generation_failed_for_session': '為 session {session_id} 生成預覽失敗: {e}',
        'preview_worker_error': '預覽生成工作線程發生錯誤: {e}',
        'ai_settings_incomplete_for_preview': 'AI 設定不完整。',
        'app_template_prompt_not_found': '找不到應用模板提示。',
        'headless_template_generation_failed': '無頭模板生成失敗: {e}',
        'risk_analysis_prompt_not_found': 'Risk analysis prompt not found in the database.',
        'no_existing_risks': '無',
        'json_missing_keys': 'Parsed JSON is missing required keys: {keys}',
        'invalid_json_response': 'AI response was not valid JSON.',
        'headless_risk_report_failed': 'Headless risk report generation failed: {e}',
        'permission_denied': '權限不足',
        'management_center': '後台管理中心',
        'management_menu': '管理選單',
        'dashboard': '系統儀表板',
        'user_management': '使用者管理',
        'app_review': '應用審核',
        'system_settings': '系統設定',
        'user_group_management': '使用者群組管理',
        'permission_management': '權限管理',
        'prompt_management': '提示詞管理',
        'dashboard_load_error': '讀取儀表板數據失敗: {e}',
        'active_users': '活躍使用者',
        'total_apps': '應用總數',
        'pending_apps': '待審核應用',
        'published_apps': '已發佈應用',
        'user_id': 'ID',
        'status': '狀態',
        'active': '啟用',
        'inactive': '停用',
        'user_load_error': '重新載入使用者資料失敗: {e}',
        'add_user': '新增使用者',
        'required_field': '必填',
        'email': '電子郵件',
        'password_placeholder': '留空則不修改密碼',
        'save': '保存',
        'user_updated_success': '使用者 {username} 已成功更新',
        'password_required_for_new_user': '新增使用者時必須設定密碼',
        'user_created_success': '使用者 {username} 已成功建立',
        'save_failed': '保存失敗: {e}',
        'confirm_delete_user_title': '確定要刪除這位使用者嗎？',
        'deleting_user_info': '即將刪除: {username} (ID: {id})',
        'user_deleted': '使用者 {username} 已被刪除',
        'delete_failed': '刪除失敗: {e}',
        'edit_user': '編輯使用者',
        'edit': '編輯',
        'delete': '刪除',
        'developer': '開發者',
        'pending_apps_load_error': '讀取待審核應用失敗: {e}',
        'review_app': '審核應用',
        'app_info': '應用資訊',
        'review_actions': '審核操作',
        'review_comments': '審核意見',
        'risk_report': '風險檢測報告',
        'generate_risk_report': '生成風險檢測報告',
        'reject': '拒絕',
        'approve': '核准',
        'app_review_decision_success': "應用「{app_name}」已{decision}",
        'app_approved_text': '核准',
        'app_rejected_text': '拒絕',
        'review_op_failed': '審核操作失敗: {e}',
        'risk_analysis': '風險分析',
        'high_risk': '高',
        'medium_risk': '中',
        'low_risk': '低',
        'no_risks_found': '未發現任何風險。',
        'no_risk_detected': '未檢測到風險',
        'suggested_categories': '建議應用類別',
        'functional_description': '功能說明',
        'operating_instructions': '操作指南',
        'app_details_not_found': '找不到應用程式的詳細資料',
        'app_missing_submitted_version': '應用程式缺少提交的版本',
        'no_description_provided': '沒有提供描述',
        'submitted_at': '提交時間',
        'app_description': '應用描述',
        'regenerate_report': '重新生成報告',
        'click_to_generate_report': '點擊按鈕以生成報告...',
        'review_dialog_open_error': '打開審核視窗失敗: {e}',
        'missing_version_info_for_report': '缺少版本資訊，無法生成報告',
        'generating_report_in_progress': '正在生成報告中，請稍候...',
        'report_generated_success': '報告生成成功',
        'report_generation_error': '報告生成時發生錯誤: {e}',
        'review': '審核',
        'production_ai_settings': '正式生成 AI 設定',
        'preview_ai_settings': '預覽 AI 設定',
        'app_publish_settings': '應用發佈設定',
        'auto_publish_on_approval': '審核通過後自動發佈',
        'settings_saved_success': '系統設定已成功保存！',
        'settings_save_error': '保存設定失敗：{e}',
        'save_settings': '保存設定',
        'settings_load_error': '讀取系統設定失敗: {e}',
        'select_group_prompt': '請從左側選擇一個群組',
        'editing_group': '正在編輯群組：{name}',
        'no_description': '無描述',
        'manage_permissions': '管理權限',
        'save_changes_permissions': '保存變更',
        'permission_load_error': '載入權限時發生錯誤: {e}',
        'no_group_selected': '未選擇群組',
        'group_permissions_updated_success': "已成功更新群組 '{name}' 的權限。",
        'group_list': '群組列表',
        'add_group': '新增群組',
        'no_groups_yet': '目前沒有群組',
        'group_list_load_error': '載入群組列表失败: {e}',
        'group_name': '群組名稱',
        'group_created_success': '群組已創建',
        'group_save_error': '保存群組失敗: {e}',
        'manage_all_permissions': '管理所有權限',
        'add_permission': '新增權限',
        'permission_name': '權限名稱',
        'permission_created_success': '權限已創建',
        'permission_save_error': '保存權限失敗: {e}',
        'confirm_delete_group_title': "確定要刪除群組 '{name}' 嗎？",
        'group_deleted_success': '群組已刪除',
        'group_delete_error': '刪除群組失敗: {e}',
        'confirm_delete_permission_title': "確定要刪除權限 '{name}' 嗎？",
        'permission_deleted_success': '權限已刪除',
        'permission_delete_error': '刪除權限失敗: {e}',
        'select_user_prompt': '請從左側選擇一位使用者',
        'editing_user': '正在編輯使用者：{username}',
        'group_load_error': '載入群組時發生錯誤: {e}',
        'no_user_selected': '未選擇使用者',
        'user_groups_updated_success': "已成功更新使用者 '{username}' 的群組。",
        'user_list': '使用者列表',
        'no_users_yet': '目前沒有使用者',
        'go_add_user': '前往新增使用者',
        'user_list_load_error': '載入使用者列表失敗，請檢查日誌以獲取詳細資訊。',
        'prompts_saved_success': '提示詞已成功保存！',
        'prompt_save_error': '保存提示詞失敗：{e}',
        'save_prompts': '保存提示詞',
        'prompt_load_error': '讀取提示詞失敗: {e}',
        'exit_management': '離開管理中心',
        'app_version_trend': '應用版本迭代趨勢',
        'versions_created_per_day': '每日創建版本數',
        'date': '日期',
        'version_count': '版本數量',
        'published_app_category_distribution': '已發佈應用的分類分佈',
        'category': '分類',
        'app_count': '應用數量',
        'no_data_available': '暫無數據',
        'other_apps': '其他狀態',
        'app_status_distribution': '應用狀態分佈',
        'app_status': '應用狀態',
       'ai_model_management': 'AI 模型管理',
       'configured_ai_models': '已配置的 AI 模型',
       'add_model': '新增模型',
       'edit_model': '編輯模型',
       'model_name': '模型名稱',
       'technical_model_name': '模型技術名稱',
       'code_generation_model': '代碼生成',
       'preview_generation_model': '預覽生成',
       'report_generation_model': '報告生成',
       'ai_model_load_error': '讀取 AI 模型失敗: {e}',
       'model_status_updated_success': '模型啟用狀態已更新',
       'model_status_update_error': '更新模型狀態失敗: {e}',
       'custom_model_name': '自訂模型名稱',
       'api_key': 'API 金鑰',
       'endpoint_url': 'API 端點網址',
       'model_updated_success': '模型已成功更新',
       'model_created_success': '模型已成功新增',
       'model_save_error': '保存模型失敗: {e}',
       'confirm_delete_model_title': '確定要刪除這個模型嗎？',
       'deleting_model_info': '即將刪除模型: {name}',
       'model_deleted_success': '模型已成功刪除',
       'model_delete_error': '刪除模型失敗: {e}',
       'general_settings': '通用設定',
       'status_draft': '草稿',
       'status_in_review': '審核中',
       'status_approved': '已批准',
       'status_rejected': '已拒絕',
       'status_published': '已發佈',
       'status_archived': '已封存',
       'status_deleted': '已刪除',
       'require_risk_report_before_approval': '在審批前必須生成風險檢測報告',
       'must_generate_report_to_approve': '必須先生成風險報告才能批准',
       'generating_report_before_submission': '正在提交前生成風險報告...',
       'report_generation_failed_before_submission': '在提交前生成報告失敗：{e}',
      'published_app_management': '已上架應用管理',
      'published_at': '發佈時間',
      'unpublish_app': '下架應用',
      'confirm_unpublish_app_title': '確定要下架此應用嗎？',
      'unpublishing_app_info': '即將下架: {name}',
      'app_unpublished_success_admin': '應用 "{name}" 已成功下架。',
      'unpublish_failed': '下架失敗: {e}',
      'operating_instructions_title': '操作指南',
      'no_instructions_provided': '未提供操作指南。',
      'app_functional_description_title': '應用說明',
      'language_chinese_traditional': '繁體中文',
      'language_chinese_simplified': '简体中文',
      'language_english': 'English',
      'language_japanese': '日本語',
      'language_korean': '한국어',
      'account_disabled': '帳號已被停用，請聯絡管理員。',
      'vibe_slogan': '從想法到應用，瞬間實現',
   },
  'zh-CN': {
      'create_session': '正在创建新会话...',
      'version_history': '版本历史',
        'download_application': '下载应用',
        'new_application': '新制作',
        'new_app': '新增应用',
        'app_store': '社区应用',
        'application_filename': '应用-{id}.url',
        'ai_suggestion': 'AI生成结果未如理想时，建议直接使用上方按钮回到之前的版本重新提出需求。',
        'conversation': '对话',
        'input_placeholder': '请描述您想要的工具...',
        'send': '发送',
        'stop': '停止',
        'tool_preview': '工具预览',
        'edit_code': '修改代码',
        'publish_app': '发布为应用',
        'generate_new_template': '为我生成新的应用模板',
        'manage_publish': '管理发布',
        'dedicated_page': '独立页面',
        'edit_code_manually': '手动修改代码',
        'cancel': '取消',
        'save_changes': '保存修改',
        'publish': '提交审核',
        'unpublish': '下架封存',
        'app_name_label': '应用名称',
        'publish_dialog_title': '发布应用',
        'app_published_success': '应用“{name}”已成功提交审核！',
        'app_unpublished_success': '应用已成功下架封存。',
        'confirm_cancel_submission_text': '您确定要取消对应用 {name} 的审核提交吗？',
        'confirm_go_live_text': '您确定要将已批准的应用 {name} 正式发布上线吗？',
        'confirm_unpublish_text': '您确定要将已发布的应用 {name} 下架封存吗？',
        'app_updated_success': '应用已更新为版本 V{v_num}。',
        'use_app': '使用应用',
        'published_mark': '（已发布）',
        'chat_you': '您',
        'chat_ai': 'AI',
        'chat_system': '系统',
        'ai_thinking': 'AI 正在思考中...',
        'ai_settings_incomplete': 'AI 设置不完整或不正确。',
        'go_to_management_for_config': '<br>请点击<a href="/management" style="text-decoration: underline; color: #3B82F6;">此处</a>前往管理中心进行设定。',
        'system_prompt_not_found': '系统提示未找到。',
        'ai_no_html': 'AI 未能生成有效的 HTML 内容。',
        'api_request_failed': '<b>API 请求失败</b>',
        'cannot_connect_ai': '<b>无法连接到 AI 服务器</b>',
        'unexpected_error': '<b>发生未预期的错误</b>:',
        'error_notification': '发生错误: {e}',
        'ai_busy_or_no_response': 'AI 服务繁忙或无响应',
        'based_on_v': '基于 V{v_num}',
        'preview_title': '版本 V{v_num}{base_text}',
        'based_on_v_suffix': ' (基于 V{v_num})',
        'code_saved_as_v': '代码已手动修改并保存为 V{v_num}。',
        'generated_v': '已为您生成 V{v_num}。',
        'request_changes_for_v': '请提出对版本 V{v_num} 的修改...',
        'cannot_save_no_base': '无法保存，没有基础版本或内容为空。',
        'saving_changes': '正在保存修改...',
        'manual_edit_request': '手动修改',
        'no_history': '无历史记录。',
        'user_request_history': '用户 (V{v_num} 的需求): {request}',
        'window_title': 'Vibe coding DEMO',
        'lang_button': '简/EN',
        'app_description_placeholder': '这是一个很棒的应用程序，可以帮助您完成很多事情。',
        'version_not_found': '找不到指定的应用程序版本',
        'share_not_found_or_expired': '分享的应用程序不存在或已过期',
        'user_login': '用户登录',
        'username': '用户名',
        'password': '密码',
        'login': '登录',
        'logout': '登出',
        'login_error': '账号或密码错误',
        'my_apps': '我的',
        'latest_apps': '最新发布的应用',
        'no_apps_in_store': '商城还没有任何应用。',
        'no_preview_available': '无可用预览',
        'preview_generation_failed': '预览生成失败',
        'generating_preview': '正在生成预览...',
        'manage': '管理',
        'you_have_no_apps': '您还没有任何应用。',
        'my_shares': '我的分享',
        'app_name': '应用名称',
        'share_link': '分享链接',
        'expires_at': '到期时间',
        'actions': '操作',
        'permanent': '永久',
        'share_link_removed': '分享链接已移除。',
        'remove_share': '移除分享',
        'copy_link': '复制链接',
        'link_copied': '链接已复制到剪贴板！',
        'you_have_no_shares': '您没有任何分享。',
        'confirm_delete_app_title': '您确定要删除这个应用吗？此操作无法复原。',
        'app_deleted': '应用已删除。',
        'confirm_delete': '确定删除',
        'close': '关闭',
        'share': '分享',
        'delete_app': '删除应用',
        'share_app_version': '分享应用版本',
        '1_day': '1 天',
        '7_days': '7 天',
        '1_month': '1 个月',
        'share_duration': '分享时长',
        'cannot_generate_share_link': '无法生成分享链接。',
        'generate_link': '生成链接',
        'share_link_generated': '分享链接已生成并复制到剪贴板！',
        'processing_request': '正在处理请求，请稍候...',
        'under_review': '管理审核中',
        'go_live': '正式发布',
        'manage_published_version': '管理已发布版本',
        'preview_generating': '预览生成中...',
        'managing_review_app': '管理审核中的应用',
        'app_approved': '应用已批准',
        'cancel_submission': '取消提交',
        'submission_cancelled': '已取消提交审核。',
        'app_live_success': '应用已成功发布上线！',
        'app_name_required': '请输入应用名称',
        'app_description_required': '请输入应用描述',
        'user_info_error': '错误：找不到用户信息，请重新登录。',
        'app_submitted_for_review': '应用已提交审核，预览图将在后台生成。',
        'publish_failed': '发布失败: {e}',
        'manual_edit_by_user': '用户手动修改了代码。',
        'welcome_message': '欢迎使用！请开始您的第一个需求',
        'archive_before_delete': '删除应用前，请先将其“下架封存”。',
        'preview_worker_started': '预览生成后台工作线程已启动。',
        'template_generation_failed': 'AI未能生成有效的预览模板。',
        'preview_generation_failed_for_session': '为 session {session_id} 生成预览失败: {e}',
        'preview_worker_error': '预览生成工作线程发生错误: {e}',
        'ai_settings_incomplete_for_preview': 'AI 设置不完整。',
        'app_template_prompt_not_found': '找不到应用模板提示。',
        'headless_template_generation_failed': '无头模板生成失败: {e}',
        'risk_analysis_prompt_not_found': 'Risk analysis prompt not found in the database.',
        'no_existing_risks': '无',
        'json_missing_keys': 'Parsed JSON is missing required keys: {keys}',
        'invalid_json_response': 'AI response was not valid JSON.',
        'headless_risk_report_failed': 'Headless risk report generation failed: {e}',
        'permission_denied': '权限不足',
        'management_center': '后台管理中心',
        'management_menu': '管理菜单',
        'dashboard': '系统仪表板',
        'user_management': '用户管理',
        'app_review': '应用审核',
        'system_settings': '系统设置',
        'user_group_management': '用户组管理',
        'permission_management': '权限管理',
        'prompt_management': '提示词管理',
        'dashboard_load_error': '读取仪表板数据失败: {e}',
        'active_users': '活跃用户',
        'total_apps': '应用总数',
        'pending_apps': '待审核应用',
        'published_apps': '已发布应用',
        'user_id': 'ID',
        'status': '状态',
        'active': '启用',
        'inactive': '停用',
        'user_load_error': '重新加载用户数据失败: {e}',
        'add_user': '新增用户',
        'required_field': '必填',
        'email': '电子邮件',
        'password_placeholder': '留空则不修改密码',
        'save': '保存',
        'user_updated_success': '用户 {username} 已成功更新',
        'password_required_for_new_user': '新增用户时必须设置密码',
        'user_created_success': '用户 {username} 已成功建立',
        'save_failed': '保存失败: {e}',
        'confirm_delete_user_title': '确定要删除这位用户吗？',
        'deleting_user_info': '即将删除: {username} (ID: {id})',
        'user_deleted': '用户 {username} 已被删除',
        'delete_failed': '删除失败: {e}',
        'edit_user': '编辑用户',
        'edit': '编辑',
        'delete': '删除',
        'developer': '开发者',
        'pending_apps_load_error': '读取待审核应用失败: {e}',
        'review_app': '审核应用',
        'app_info': '应用信息',
        'review_actions': '审核操作',
        'review_comments': '审核意见',
        'risk_report': '风险检测报告',
        'generate_risk_report': '生成风险检测报告',
        'reject': '拒绝',
        'approve': '核准',
        'app_review_decision_success': "应用“{app_name}”已{decision}",
        'app_approved_text': '核准',
        'app_rejected_text': '拒绝',
        'review_op_failed': '审核操作失败: {e}',
        'risk_analysis': '风险分析',
        'high_risk': '高',
        'medium_risk': '中',
        'low_risk': '低',
        'no_risks_found': '未发现任何风险。',
        'no_risk_detected': '未检测到风险',
        'suggested_categories': '建议应用类别',
        'functional_description': '功能说明',
        'operating_instructions': '操作指南',
        'app_details_not_found': '找不到应用程序的详细资料',
        'app_missing_submitted_version': '应用程序缺少提交的版本',
        'no_description_provided': '没有提供描述',
        'submitted_at': '提交时间',
        'app_description': '应用描述',
        'regenerate_report': '重新生成报告',
        'click_to_generate_report': '点击按钮以生成报告...',
        'review_dialog_open_error': '打开审核窗口失败: {e}',
        'missing_version_info_for_report': '缺少版本信息，无法生成报告',
        'generating_report_in_progress': '正在生成报告中，请稍候...',
        'report_generated_success': '报告生成成功',
        'report_generation_error': '报告生成时发生错误: {e}',
        'review': '审核',
        'production_ai_settings': '正式生成 AI 设置',
        'preview_ai_settings': '预览 AI 设置',
        'app_publish_settings': '应用发布设置',
        'auto_publish_on_approval': '审核通过后自动发布',
        'settings_saved_success': '系统设置已成功保存！',
        'settings_save_error': '保存设置失败：{e}',
        'save_settings': '保存设置',
        'settings_load_error': '读取系统设置失败: {e}',
        'select_group_prompt': '请从左侧选择一个群组',
        'editing_group': '正在编辑群组：{name}',
        'no_description': '无描述',
        'manage_permissions': '管理权限',
        'save_changes_permissions': '保存变更',
        'permission_load_error': '加载权限时发生错误: {e}',
        'no_group_selected': '未选择群组',
        'group_permissions_updated_success': "已成功更新群组“{name}”的权限。",
        'group_list': '群组列表',
        'add_group': '新增群组',
        'no_groups_yet': '目前没有群组',
        'group_list_load_error': '加载群组列表失败: {e}',
        'group_name': '群组名称',
        'group_created_success': '群组已创建',
        'group_save_error': '保存群组失败: {e}',
        'manage_all_permissions': '管理所有权限',
        'add_permission': '新增权限',
        'permission_name': '权限名称',
        'permission_created_success': '权限已创建',
        'permission_save_error': '保存权限失败: {e}',
        'confirm_delete_group_title': "确定要删除群组“{name}”吗？",
        'group_deleted_success': '群组已删除',
        'group_delete_error': '删除群组失败: {e}',
        'confirm_delete_permission_title': "确定要删除权限“{name}”吗？",
        'permission_deleted_success': '权限已删除',
        'permission_delete_error': '删除权限失败: {e}',
        'select_user_prompt': '请从左侧选择一位用户',
        'editing_user': '正在编辑用户：{username}',
        'group_load_error': '加载群组时发生错误: {e}',
        'no_user_selected': '未选择用户',
        'user_groups_updated_success': "已成功更新用户“{username}”的群组。",
        'user_list': '用户列表',
        'no_users_yet': '目前没有用户',
        'go_add_user': '前往新增用户',
        'user_list_load_error': '加载用户列表失败，请检查日志以获取详细信息。',
        'prompts_saved_success': '提示词已成功保存！',
        'prompt_save_error': '保存提示词失败：{e}',
        'save_prompts': '保存提示词',
        'prompt_load_error': '读取提示词失败: {e}',
        'exit_management': '离开管理中心',
        'app_version_trend': '应用版本迭代趋势',
        'versions_created_per_day': '每日创建版本数',
        'date': '日期',
        'version_count': '版本数量',
        'published_app_category_distribution': '已发布应用的分类分布',
        'category': '分类',
        'app_count': '应用数量',
        'no_data_available': '暂无数据',
        'other_apps': '其他状态',
        'app_status_distribution': '应用状态分布',
        'app_status': '应用状态',
        'ai_model_management': 'AI 模型管理',
        'configured_ai_models': '已配置的 AI 模型',
        'add_model': '新增模型',
        'edit_model': '编辑模型',
        'model_name': '模型名称',
        'technical_model_name': '模型技术名称',
        'code_generation_model': '代码生成',
        'preview_generation_model': '预览生成',
        'report_generation_model': '报告生成',
        'ai_model_load_error': '读取 AI 模型失败: {e}',
        'model_status_updated_success': '模型启用状态已更新',
        'model_status_update_error': '更新模型状态失败: {e}',
        'custom_model_name': '自定义模型名称',
        'api_key': 'API 密钥',
        'endpoint_url': 'API 端点网址',
        'model_updated_success': '模型已成功更新',
        'model_created_success': '模型已成功新增',
        'model_save_error': '保存模型失败: {e}',
        'confirm_delete_model_title': '确定要删除这个模型吗？',
        'deleting_model_info': '即将删除模型: {name}',
        'model_deleted_success': '模型已成功删除',
        'model_delete_error': '删除模型失败: {e}',
        'general_settings': '通用设置',
        'status_draft': '草稿',
        'status_in_review': '审核中',
        'status_approved': '已批准',
        'status_rejected': '已拒绝',
        'status_published': '已发布',
        'status_archived': '已封存',
        'status_deleted': '已删除',
        'require_risk_report_before_approval': '在审批前必须生成风险检测报告',
        'must_generate_report_to_approve': '必须先生成风险报告才能批准',
        'generating_report_before_submission': '正在提交前生成风险报告...',
        'report_generation_failed_before_submission': '在提交前生成报告失败：{e}',
        'published_app_management': '已上架应用管理',
        'published_at': '发布时间',
        'unpublish_app': '下架应用',
        'confirm_unpublish_app_title': '确定要下架此应用吗？',
        'unpublishing_app_info': '即将下架: {name}',
        'app_unpublished_success_admin': '应用“{name}”已成功下架。',
        'unpublish_failed': '下架失败: {e}',
        'operating_instructions_title': '操作指南',
        'no_instructions_provided': '未提供操作指南。',
        'app_functional_description_title': '应用说明',
        'language_chinese_traditional': '繁體中文',
        'language_chinese_simplified': '简体中文',
        'language_english': 'English',
        'language_japanese': '日本語',
        'language_korean': '한국어',
        'account_disabled': '账号已被停用，请联系管理员。',
        'vibe_slogan': '从想法到应用，瞬间实现',
        },
        'go_to_management_for_config': '<br>请点击<a href="/management" style="text-decoration: underline; color: #3B82F6;">此处</a>前往管理中心进行设定。',
    'ja': {
        'create_session': '新しいセッションを作成中...',
        'version_history': 'バージョン履歴',
        'download_application': 'アプリケーションをダウンロード',
        'new_application': '新規作成',
        'new_app': '新しいアプリ',
        'app_store': 'コミュニティアプリ',
        'application_filename': 'アプリ-{id}.url',
        'ai_suggestion': 'AIの生成結果が期待通りでない場合は、上のボタンで前のバージョンに戻って再度リクエストを提出することをお勧めします。',
        'conversation': '会話',
        'input_placeholder': '欲しいツールを説明してください...',
        'send': '送信',
        'stop': '停止',
        'tool_preview': 'ツールプレビュー',
        'edit_code': 'コードを編集',
        'publish_app': 'アプリとして公開',
        'generate_new_template': '新しいアプリのテンプレートを生成',
        'manage_publish': '公開を管理',
        'dedicated_page': '専用ページ',
        'edit_code_manually': '手動でコードを編集',
        'cancel': 'キャンセル',
        'save_changes': '変更を保存',
        'publish': 'レビュー用に送信',
        'unpublish': '公開停止してアーカイブ',
        'app_name_label': 'アプリ名',
        'publish_dialog_title': 'アプリを公開',
        'app_published_success': 'アプリ「{name}」がレビュー用に正常に送信されました！',
        'app_unpublished_success': 'アプリは正常に公開停止され、アーカイブされました。',
        'confirm_cancel_submission_text': 'アプリケーション {name} のレビュー提出をキャンセルしてもよろしいですか？',
        'confirm_go_live_text': '承認済みのアプリケーション {name} を公開してもよろしいですか？',
        'confirm_unpublish_text': '公開中のアプリケーション {name} を公開停止してアーカイブしてもよろしいですか？',
        'app_updated_success': 'アプリはバージョン V{v_num} に更新されました。',
        'use_app': 'アプリを使用',
        'published_mark': '（公開済み）',
        'chat_you': 'あなた',
        'chat_ai': 'AI',
        'chat_system': 'システム',
        'ai_thinking': 'AIが思考中...',
        'ai_settings_incomplete': 'AIの設定が不完全または正しくありません。',
        'go_to_management_for_config': '<br><a href="/management" style="text-decoration: underline; color: #3B82F6;">こちら</a>をクリックして管理センターで設定してください。',
        'system_prompt_not_found': 'システムプロンプトが見つかりません。',
        'ai_no_html': 'AIは有効なHTMLコンテンツを生成できませんでした。',
        'api_request_failed': '<b>APIリクエストに失敗しました</b>',
        'cannot_connect_ai': '<b>AIサーバーに接続できませんでした</b>',
        'unexpected_error': '<b>予期せぬエラーが発生しました</b>:',
        'error_notification': 'エラーが発生しました: {e}',
        'ai_busy_or_no_response': 'AIサービスがビジー状態か、応答がありません',
        'based_on_v': 'V{v_num}に基づく',
        'preview_title': 'バージョン V{v_num}{base_text}',
        'based_on_v_suffix': ' (V{v_num}に基づく)',
        'code_saved_as_v': 'コードは手動で変更され、V{v_num}として保存されました。',
        'generated_v': 'V{v_num}を生成しました。',
        'request_changes_for_v': 'バージョン V{v_num} の変更点を提出してください...',
        'cannot_save_no_base': '保存できません。基本バージョンがないか、内容が空です。',
        'saving_changes': '変更を保存中...',
        'manual_edit_request': '手動編集',
        'no_history': '履歴がありません。',
        'user_request_history': 'ユーザー (V{v_num}のリクエスト): {request}',
        'window_title': 'Vibe coding DEMO',
        'lang_button': '日/EN',
        'app_description_placeholder': 'これは多くのことを手助けできる素晴らしいアプリケーションです。',
        'version_not_found': '指定されたアプリケーションのバージョンが見つかりませんでした',
        'share_not_found_or_expired': '共有されたアプリケーションが存在しないか、期限切れです',
        'user_login': 'ユーザーログイン',
        'username': 'ユーザー名',
        'password': 'パスワード',
        'login': 'ログイン',
        'logout': 'ログアウト',
        'login_error': 'アカウントまたはパスワードが間違っています',
        'my_apps': 'マイアプリ',
        'latest_apps': '最新公開アプリ',
        'no_apps_in_store': 'ストアにはまだアプリケーションがありません。',
        'no_preview_available': '利用可能なプレビューはありません',
        'preview_generation_failed': 'プレビューの生成に失敗しました',
        'generating_preview': 'プレビューを生成中...',
        'manage': '管理',
        'you_have_no_apps': 'まだアプリケーションがありません。',
        'my_shares': 'マイシェア',
        'app_name': 'アプリ名',
        'share_link': '共有リンク',
        'expires_at': '有効期限',
        'actions': '操作',
        'permanent': '無期限',
        'share_link_removed': '共有リンクは削除されました。',
        'remove_share': '共有を削除',
        'copy_link': 'リンクをコピー',
        'link_copied': 'リンクがクリップボードにコピーされました！',
        'you_have_no_shares': '共有はありません。',
        'confirm_delete_app_title': 'このアプリケーションを削除してもよろしいですか？この操作は元に戻せません。',
        'app_deleted': 'アプリケーションは削除されました。',
        'confirm_delete': '削除を確認',
        'close': '閉じる',
        'share': '共有',
        'delete_app': 'アプリを削除',
        'share_app_version': 'アプリのバージョンを共有',
        '1_day': '1日',
        '7_days': '7日間',
        '1_month': '1ヶ月',
        'share_duration': '共有期間',
        'cannot_generate_share_link': '共有リンクを生成できませんでした。',
        'generate_link': 'リンクを生成',
        'share_link_generated': '共有リンクが生成され、クリップボードにコピーされました！',
        'processing_request': 'リクエストを処理しています、しばらくお待ちください...',
        'under_review': 'レビュー中',
        'go_live': '公開',
        'manage_published_version': '公開済みバージョンを管理',
        'preview_generating': 'プレビューを生成中...',
        'managing_review_app': 'レビュー中のアプリを管理',
        'app_approved': 'アプリは承認されました',
        'cancel_submission': '提出をキャンセル',
        'submission_cancelled': 'レビューの提出はキャンセルされました。',
        'app_live_success': 'アプリは正常に公開されました！',
        'app_name_required': 'アプリ名を入力してください',
        'app_description_required': 'アプリの説明を入力してください',
        'user_info_error': 'エラー：ユーザー情報が見つかりません。再度ログインしてください。',
        'app_submitted_for_review': 'アプリはレビュー用に送信されました。プレビューはバックグラウンドで生成されます。',
        'publish_failed': '公開に失敗しました: {e}',
        'manual_edit_by_user': 'ユーザーが手動でコードを変更しました。',
        'welcome_message': 'ようこそ！最初のリクエストを開始してください',
        'archive_before_delete': 'アプリを削除する前に、「公開停止してアーカイブ」してください。',
        'preview_worker_started': 'プレビュー生成のバックグラウンドワーカースレッドが開始されました。',
        'template_generation_failed': 'AIは有効なプレビューテンプレートを生成できませんでした。',
        'preview_generation_failed_for_session': 'セッション {session_id} のプレビュー生成に失敗しました: {e}',
        'preview_worker_error': 'プレビュー生成ワーカースレッドでエラーが発生しました: {e}',
        'ai_settings_incomplete_for_preview': 'AIの設定が不完全です。',
        'app_template_prompt_not_found': 'アプリテンプレートのプロンプトが見つかりません。',
        'headless_template_generation_failed': 'ヘッドレスモードでのテンプレート生成に失敗しました: {e}',
        'risk_analysis_prompt_not_found': 'データベースにリスク分析プロンプトが見つかりません。',
        'no_existing_risks': 'なし',
        'json_missing_keys': '解析されたJSONに必要なキーがありません: {keys}',
        'invalid_json_response': 'AIの応答は有効なJSONではありませんでした。',
        'headless_risk_report_failed': 'ヘッドレスモードでのリスクレポート生成に失敗しました: {e}',
        'permission_denied': '権限がありません',
        'management_center': '管理センター',
        'management_menu': '管理メニュー',
        'dashboard': 'ダッシュボード',
        'user_management': 'ユーザー管理',
        'app_review': 'アプリレビュー',
        'system_settings': 'システム設定',
        'user_group_management': 'ユーザーグループ管理',
        'permission_management': '権限管理',
        'prompt_management': 'プロンプト管理',
        'dashboard_load_error': 'ダッシュボードデータの読み込みに失敗しました: {e}',
        'active_users': 'アクティブユーザー',
        'total_apps': '総アプリ数',
        'pending_apps': '保留中のアプリ',
        'published_apps': '公開済みアプリ',
        'user_id': 'ID',
        'status': 'ステータス',
        'active': '有効',
        'inactive': '無効',
        'user_load_error': 'ユーザーデータの再読み込みに失敗しました: {e}',
        'add_user': 'ユーザーを追加',
        'required_field': '必須',
        'email': 'Eメール',
        'password_placeholder': 'パスワードを変更しない場合は空のままにしてください',
        'save': '保存',
        'user_updated_success': 'ユーザー {username} は正常に更新されました',
        'password_required_for_new_user': '新しいユーザーを作成する際にはパスワードが必要です',
        'user_created_success': 'ユーザー {username} は正常に作成されました',
        'save_failed': '保存に失敗しました: {e}',
        'confirm_delete_user_title': 'このユーザーを削除してもよろしいですか？',
        'deleting_user_info': '削除対象: {username} (ID: {id})',
        'user_deleted': 'ユーザー {username} は削除されました',
        'delete_failed': '削除に失敗しました: {e}',
        'edit_user': 'ユーザーを編集',
        'edit': '編集',
        'delete': '削除',
        'developer': '開発者',
        'pending_apps_load_error': '保留中のアプリケーションの読み込みに失敗しました: {e}',
        'review_app': 'アプリをレビュー',
        'app_info': 'アプリ情報',
        'review_actions': 'レビュー操作',
        'review_comments': 'レビューコメント',
        'risk_report': 'リスク検出レポート',
        'generate_risk_report': 'リスク検出レポートを生成',
        'reject': '拒否',
        'approve': '承認',
        'app_review_decision_success': "アプリ「{app_name}」は{decision}されました",
        'app_approved_text': '承認',
        'app_rejected_text': '拒否',
        'review_op_failed': 'レビュー操作に失敗しました: {e}',
        'risk_analysis': 'リスク分析',
        'high_risk': '高',
        'medium_risk': '中',
        'low_risk': '低',
        'no_risks_found': 'リスクは見つかりませんでした。',
        'no_risk_detected': 'リスクは検出されませんでした',
        'suggested_categories': '推奨アプリカテゴリ',
        'functional_description': '機能説明',
        'operating_instructions': '操作ガイド',
        'app_details_not_found': 'アプリケーションの詳細が見つかりません',
        'app_missing_submitted_version': 'アプリケーションに提出されたバージョンがありません',
        'no_description_provided': '説明が提供されていません',
        'submitted_at': '提出日時',
        'app_description': 'アプリの説明',
        'regenerate_report': 'レポートを再生成',
        'click_to_generate_report': 'ボタンをクリックしてレポートを生成...',
        'review_dialog_open_error': 'レビューウィンドウを開けませんでした: {e}',
        'missing_version_info_for_report': 'バージョン情報が不足しているため、レポートを生成できません',
        'generating_report_in_progress': 'レポートを生成中です、しばらくお待ちください...',
        'report_generated_success': 'レポートは正常に生成されました',
        'report_generation_error': 'レポート生成中にエラーが発生しました: {e}',
        'review': 'レビュー',
        'production_ai_settings': '本番生成AI設定',
        'preview_ai_settings': 'プレビューAI設定',
        'app_publish_settings': 'アプリ公開設定',
        'auto_publish_on_approval': '承認後自動公開',
        'settings_saved_success': 'システム設定が正常に保存されました！',
        'settings_save_error': '設定の保存に失敗しました：{e}',
        'save_settings': '設定を保存',
        'settings_load_error': 'システム設定の読み込みに失敗しました: {e}',
        'select_group_prompt': '左からグループを選択してください',
        'editing_group': '編集中グループ：{name}',
        'no_description': '説明なし',
        'manage_permissions': '権限を管理',
        'save_changes_permissions': '変更を保存',
        'permission_load_error': '権限の読み込み中にエラーが発生しました: {e}',
        'no_group_selected': 'グループが選択されていません',
        'group_permissions_updated_success': "グループ「{name}」の権限が正常に更新されました。",
        'group_list': 'グループリスト',
        'add_group': 'グループを追加',
        'no_groups_yet': 'まだグループがありません',
        'group_list_load_error': 'グループリストの読み込みに失敗しました: {e}',
        'group_name': 'グループ名',
        'group_created_success': 'グループが作成されました',
        'group_save_error': 'グループの保存に失敗しました: {e}',
        'manage_all_permissions': 'すべての権限を管理',
        'add_permission': '権限を追加',
        'permission_name': '権限名',
        'permission_created_success': '権限が作成されました',
        'permission_save_error': '権限の保存に失敗しました: {e}',
        'confirm_delete_group_title': "グループ「{name}」を削除してもよろしいですか？",
        'group_deleted_success': 'グループは削除されました',
        'group_delete_error': 'グループの削除に失敗しました: {e}',
        'confirm_delete_permission_title': "権限「{name}」を削除してもよろしいですか？",
        'permission_deleted_success': '権限は削除されました',
        'permission_delete_error': '権限の削除に失敗しました: {e}',
        'select_user_prompt': '左からユーザーを選択してください',
        'editing_user': '編集中ユーザー：{username}',
        'group_load_error': 'グループの読み込み中にエラーが発生しました: {e}',
        'no_user_selected': 'ユーザーが選択されていません',
        'user_groups_updated_success': "ユーザー「{username}」のグループが正常に更新されました。",
        'user_list': 'ユーザーリスト',
        'no_users_yet': 'まだユーザーがいません',
        'go_add_user': 'ユーザー追加へ',
        'user_list_load_error': 'ユーザーリストの読み込みに失敗しました。詳細はログを確認してください。',
        'prompts_saved_success': 'プロンプトは正常に保存されました！',
        'prompt_save_error': 'プロンプトの保存に失敗しました：{e}',
        'save_prompts': 'プロンプトを保存',
        'prompt_load_error': 'プロンプトの読み込みに失敗しました: {e}',
        'exit_management': '管理センターを終了',
        'app_version_trend': 'アプリバージョン迭代トレンド',
        'versions_created_per_day': '一日あたりの作成バージョン数',
        'date': '日付',
        'version_count': 'バージョン数',
        'published_app_category_distribution': '公開済みアプリのカテゴリ分布',
        'category': 'カテゴリ',
        'app_count': 'アプリ数',
        'no_data_available': 'データがありません',
        'other_apps': 'その他のステータス',
        'app_status_distribution': 'アプリステータス分布',
        'app_status': 'アプリステータス',
        'ai_model_management': 'AIモデル管理',
        'configured_ai_models': '設定済みAIモデル',
        'add_model': 'モデルを追加',
        'edit_model': 'モデルを編集',
        'model_name': 'モデル名',
        'technical_model_name': 'モデル技術名',
        'code_generation_model': 'コード生成',
        'preview_generation_model': 'プレビュー生成',
        'report_generation_model': 'レポート生成',
        'ai_model_load_error': 'AIモデルの読み込みに失敗しました: {e}',
        'model_status_updated_success': 'モデルの有効化ステータスが更新されました',
        'model_status_update_error': 'モデルステータスの更新に失敗しました: {e}',
        'custom_model_name': 'カスタムモデル名',
        'api_key': 'APIキー',
        'endpoint_url': 'APIエンドポイントURL',
        'model_updated_success': 'モデルは正常に更新されました',
        'model_created_success': 'モデルは正常に追加されました',
        'model_save_error': 'モデルの保存に失敗しました: {e}',
        'confirm_delete_model_title': 'このモデルを削除してもよろしいですか？',
        'deleting_model_info': '削除するモデル: {name}',
        'model_deleted_success': 'モデルは正常に削除されました',
        'model_delete_error': 'モデルの削除に失敗しました: {e}',
        'general_settings': '一般設定',
        'status_draft': '下書き',
        'status_in_review': 'レビュー中',
        'status_approved': '承認済み',
        'status_rejected': '拒否済み',
        'status_published': '公開済み',
        'status_archived': 'アーカイブ済み',
        'status_deleted': '削除済み',
        'require_risk_report_before_approval': '承認前にリスク検出レポートの生成が必要',
        'must_generate_report_to_approve': '承認するにはまずリスクレポートを生成する必要があります',
        'generating_report_before_submission': '提出前にリスクレポートを生成中...',
        'report_generation_failed_before_submission': '提出前のレポート生成に失敗しました：{e}',
        'published_app_management': '公開済みアプリ管理',
        'published_at': '公開日時',
        'unpublish_app': 'アプリの公開を停止',
        'confirm_unpublish_app_title': 'このアプリの公開を停止してもよろしいですか？',
        'unpublishing_app_info': '公開停止対象: {name}',
        'app_unpublished_success_admin': 'アプリ「{name}」は正常に公開停止されました。',
        'unpublish_failed': '公開停止に失敗しました: {e}',
        'operating_instructions_title': '操作ガイド',
        'no_instructions_provided': '操作ガイドは提供されていません。',
        'app_functional_description_title': 'アプリ説明',
        'language_chinese_traditional': '繁體中文',
        'language_chinese_simplified': '简体中文',
        'language_english': 'English',
        'language_japanese': '日本語',
        'language_korean': '한국어',
        'account_disabled': 'アカウントが無効化されています。管理者に連絡してください。',
        'vibe_slogan': 'アイデアからアプリケーションへ、瞬時に',
        },
        'go_to_management_for_config': '<br><a href="/management" style="text-decoration: underline; color: #3B82F6;">こちら</a>をクリックして管理センターで設定してください。',
    'ko': {
        'create_session': '새 세션 만드는 중...',
        'version_history': '버전 기록',
        'download_application': '애플리케이션 다운로드',
        'new_application': '새로 만들기',
        'new_app': '새 앱',
        'app_store': '커뮤니티 앱',
        'application_filename': '앱-{id}.url',
        'ai_suggestion': 'AI 생성 결과가 기대에 미치지 못할 경우, 위 버튼을 사용하여 이전 버전으로 돌아가 요청을 다시 제출하는 것이 좋습니다.',
        'conversation': '대화',
        'input_placeholder': '원하는 도구를 설명해주세요...',
        'send': '전송',
        'stop': '중지',
        'tool_preview': '도구 미리보기',
        'edit_code': '코드 수정',
        'publish_app': '앱으로 게시',
        'generate_new_template': '새 앱 템플릿 생성',
        'manage_publish': '게시 관리',
        'dedicated_page': '전용 페이지',
        'edit_code_manually': '수동으로 코드 수정',
        'cancel': '취소',
        'save_changes': '변경 사항 저장',
        'publish': '검토용으로 제출',
        'unpublish': '게시 취소 및 보관',
        'app_name_label': '앱 이름',
        'publish_dialog_title': '앱 게시',
        'app_published_success': '앱 "{name}"이(가) 성공적으로 검토용으로 제출되었습니다!',
        'app_unpublished_success': '앱이 성공적으로 게시 취소 및 보관되었습니다.',
        'confirm_cancel_submission_text': '앱 {name}에 대한 검토 제출을 취소하시겠습니까?',
        'confirm_go_live_text': '승인된 앱 {name}을(를) 정식으로 게시하시겠습니까?',
        'confirm_unpublish_text': '게시된 앱 {name}을(를) 게시 취소하고 보관하시겠습니까?',
        'app_updated_success': '앱이 버전 V{v_num}(으)로 업데이트되었습니다.',
        'use_app': '앱 사용',
        'published_mark': '(게시됨)',
        'chat_you': '당신',
        'chat_ai': 'AI',
        'chat_system': '시스템',
        'ai_thinking': 'AI가 생각 중...',
        'ai_settings_incomplete': 'AI 설정이 불완전하거나 올바르지 않습니다.',
        'go_to_management_for_config': '<br>관리 센터로 이동하려면 <a href="/management" style="text-decoration: underline; color: #3B82F6;">여기</a>를 클릭하여 설정하십시오.',
        'system_prompt_not_found': '시스템 프롬프트를 찾을 수 없습니다.',
        'ai_no_html': 'AI가 유효한 HTML 콘텐츠를 생성하지 못했습니다.',
        'api_request_failed': '<b>API 요청 실패</b>',
        'cannot_connect_ai': '<b>AI 서버에 연결할 수 없습니다</b>',
        'unexpected_error': '<b>예기치 않은 오류가 발생했습니다</b>:',
        'error_notification': '오류 발생: {e}',
        'ai_busy_or_no_response': 'AI 서비스가忙しいか 응답이 없습니다',
        'based_on_v': 'V{v_num} 기반',
        'preview_title': '버전 V{v_num}{base_text}',
        'based_on_v_suffix': ' (V{v_num} 기반)',
        'code_saved_as_v': '코드가 수동으로 수정되어 V{v_num}(으)로 저장되었습니다.',
        'generated_v': 'V{v_num}이(가) 생성되었습니다.',
        'request_changes_for_v': '버전 V{v_num}에 대한 변경 사항을 제출해주세요...',
        'cannot_save_no_base': '저장할 수 없습니다. 기본 버전이 없거나 내용이 비어 있습니다.',
        'saving_changes': '변경 사항 저장 중...',
        'manual_edit_request': '수동 수정',
        'no_history': '기록 없음.',
        'user_request_history': '사용자 (V{v_num} 요청): {request}',
        'window_title': 'Vibe coding DEMO',
        'lang_button': '한/EN',
        'app_description_placeholder': '이것은 많은 일을 도와줄 수 있는 훌륭한 애플리케이션입니다.',
        'version_not_found': '지정된 애플리케이션 버전을 찾을 수 없습니다',
        'share_not_found_or_expired': '공유된 애플리케이션이 존재하지 않거나 만료되었습니다',
        'user_login': '사용자 로그인',
        'username': '사용자 이름',
        'password': '비밀번호',
        'login': '로그인',
        'logout': '로그아웃',
        'login_error': '계정 또는 비밀번호가 잘못되었습니다',
        'my_apps': '내 앱',
        'latest_apps': '최신 게시 앱',
        'no_apps_in_store': '스토어에 아직 애플리케이션이 없습니다.',
        'no_preview_available': '사용 가능한 미리보기 없음',
        'preview_generation_failed': '미리보기 생성 실패',
        'generating_preview': '미리보기 생성 중...',
        'manage': '관리',
        'you_have_no_apps': '아직 애플리케이션이 없습니다.',
        'my_shares': '내 공유',
        'app_name': '앱 이름',
        'share_link': '공유 링크',
        'expires_at': '만료 날짜',
        'actions': '작업',
        'permanent': '영구',
        'share_link_removed': '공유 링크가 제거되었습니다.',
        'remove_share': '공유 제거',
        'copy_link': '링크 복사',
        'link_copied': '링크가 클립보드에 복사되었습니다!',
        'you_have_no_shares': '공유가 없습니다.',
        'confirm_delete_app_title': '이 애플리케이션을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
        'app_deleted': '애플리케이션이 삭제되었습니다.',
        'confirm_delete': '삭제 확인',
        'close': '닫기',
        'share': '공유',
        'delete_app': '앱 삭제',
        'share_app_version': '앱 버전 공유',
        '1_day': '1일',
        '7_days': '7일',
        '1_month': '1개월',
        'share_duration': '공유 기간',
        'cannot_generate_share_link': '공유 링크를 생성할 수 없습니다.',
        'generate_link': '링크 생성',
        'share_link_generated': '공유 링크가 생성되어 클립보드에 복사되었습니다!',
        'processing_request': '요청을 처리 중입니다. 잠시만 기다려주세요...',
        'under_review': '검토 중',
        'go_live': '게시',
        'manage_published_version': '게시된 버전 관리',
        'preview_generating': '미리보기 생성 중...',
        'managing_review_app': '검토 중인 앱 관리',
        'app_approved': '앱이 승인되었습니다',
        'cancel_submission': '제출 취소',
        'submission_cancelled': '검토 제출이 취소되었습니다.',
        'app_live_success': '앱이 성공적으로 게시되었습니다!',
        'app_name_required': '앱 이름을 입력하세요',
        'app_description_required': '앱 설명을 입력하세요',
        'user_info_error': '오류: 사용자 정보를 찾을 수 없습니다. 다시 로그인해주세요.',
        'app_submitted_for_review': '앱이 검토용으로 제출되었습니다. 미리보기는 백그라운드에서 생성됩니다.',
        'publish_failed': '게시 실패: {e}',
        'manual_edit_by_user': '사용자가 수동으로 코드를 수정했습니다.',
        'welcome_message': '환영합니다! 첫 번째 요청을 시작해주세요',
        'archive_before_delete': '앱을 삭제하기 전에 "게시 취소 및 보관"해주세요.',
        'preview_worker_started': '미리보기 생성 백그라운드 워커 스레드가 시작되었습니다.',
        'template_generation_failed': 'AI가 유효한 미리보기 템플릿을 생성하지 못했습니다.',
        'preview_generation_failed_for_session': '세션 {session_id}에 대한 미리보기 생성 실패: {e}',
        'preview_worker_error': '미리보기 생성 워커 스레드에서 오류가 발생했습니다: {e}',
        'ai_settings_incomplete_for_preview': 'AI 설정이 불완전합니다.',
        'app_template_prompt_not_found': '앱 템플릿 프롬프트를 찾을 수 없습니다.',
        'headless_template_generation_failed': '헤드리스 모드 템플릿 생성 실패: {e}',
        'risk_analysis_prompt_not_found': '데이터베이스에서 리스크 분석 프롬프트를 찾을 수 없습니다.',
        'no_existing_risks': '없음',
        'json_missing_keys': '파싱된 JSON에 필요한 키가 없습니다: {keys}',
        'invalid_json_response': 'AI 응답이 유효한 JSON이 아닙니다.',
        'headless_risk_report_failed': '헤드리스 모드 리스크 보고서 생성 실패: {e}',
        'permission_denied': '권한이 없습니다',
        'management_center': '관리 센터',
        'management_menu': '관리 메뉴',
        'dashboard': '대시보드',
        'user_management': '사용자 관리',
        'app_review': '앱 검토',
        'system_settings': '시스템 설정',
        'user_group_management': '사용자 그룹 관리',
        'permission_management': '권한 관리',
        'prompt_management': '프롬프트 관리',
        'dashboard_load_error': '대시보드 데이터 로드 실패: {e}',
        'active_users': '활성 사용자',
        'total_apps': '총 앱 수',
        'pending_apps': '대기 중인 앱',
        'published_apps': '게시된 앱',
        'user_id': 'ID',
        'status': '상태',
        'active': '활성',
        'inactive': '비활성',
        'user_load_error': '사용자 데이터 다시 로드 실패: {e}',
        'add_user': '사용자 추가',
        'required_field': '필수',
        'email': '이메일',
        'password_placeholder': '현재 비밀번호를 유지하려면 비워두세요',
        'save': '저장',
        'user_updated_success': '사용자 {username}이(가) 성공적으로 업데이트되었습니다',
        'password_required_for_new_user': '새 사용자를 만들 때 비밀번호가 필요합니다',
        'user_created_success': '사용자 {username}이(가) 성공적으로 생성되었습니다',
        'save_failed': '저장 실패: {e}',
        'confirm_delete_user_title': '이 사용자를 삭제하시겠습니까?',
        'deleting_user_info': '삭제 대상: {username} (ID: {id})',
        'user_deleted': '사용자 {username}이(가) 삭제되었습니다',
        'delete_failed': '삭제 실패: {e}',
        'edit_user': '사용자 수정',
        'edit': '수정',
        'delete': '삭제',
        'developer': '개발자',
        'pending_apps_load_error': '대기 중인 애플리케이션 로드 실패: {e}',
        'review_app': '앱 검토',
        'app_info': '앱 정보',
        'review_actions': '검토 작업',
        'review_comments': '검토 의견',
        'risk_report': '위험 탐지 보고서',
        'generate_risk_report': '위험 탐지 보고서 생성',
        'reject': '거부',
        'approve': '승인',
        'app_review_decision_success': "앱 '{app_name}'이(가) {decision}되었습니다",
        'app_approved_text': '승인됨',
        'app_rejected_text': '거부됨',
        'review_op_failed': '검토 작업 실패: {e}',
        'risk_analysis': '위험 분석',
        'high_risk': '높음',
        'medium_risk': '중간',
        'low_risk': '낮음',
        'no_risks_found': '위험이 발견되지 않았습니다.',
        'no_risk_detected': '위험이 감지되지 않았습니다',
        'suggested_categories': '추천 앱 카테고리',
        'functional_description': '기능 설명',
        'operating_instructions': '작동 지침',
        'app_details_not_found': '애플리케이션 세부 정보를 찾을 수 없습니다',
        'app_missing_submitted_version': '애플리케이션에 제출된 버전이 없습니다',
        'no_description_provided': '설명이 제공되지 않았습니다',
        'submitted_at': '제출 시간',
        'app_description': '앱 설명',
        'regenerate_report': '보고서 다시 생성',
        'click_to_generate_report': '버튼을 클릭하여 보고서 생성...',
        'review_dialog_open_error': '검토 창을 열지 못했습니다: {e}',
        'missing_version_info_for_report': '버전 정보가 없어 보고서를 생성할 수 없습니다',
        'generating_report_in_progress': '보고서 생성 중, 잠시만 기다려주세요...',
        'report_generated_success': '보고서가 성공적으로 생성되었습니다',
        'report_generation_error': '보고서 생성 중 오류 발생: {e}',
        'review': '검토',
        'production_ai_settings': '프로덕션 생성 AI 설정',
        'preview_ai_settings': '미리보기 AI 설정',
        'app_publish_settings': '앱 게시 설정',
        'auto_publish_on_approval': '승인 시 자동 게시',
        'settings_saved_success': '시스템 설정이 성공적으로 저장되었습니다!',
        'settings_save_error': '설정 저장 실패: {e}',
        'save_settings': '설정 저장',
        'settings_load_error': '시스템 설정 로드 실패: {e}',
        'select_group_prompt': '왼쪽에서 그룹을 선택하세요',
        'editing_group': '편집 중인 그룹: {name}',
        'no_description': '설명 없음',
        'manage_permissions': '권한 관리',
        'save_changes_permissions': '변경 사항 저장',
        'permission_load_error': '권한 로드 중 오류 발생: {e}',
        'no_group_selected': '선택된 그룹 없음',
        'group_permissions_updated_success': "그룹 '{name}'의 권한이 성공적으로 업데이트되었습니다.",
        'group_list': '그룹 목록',
        'add_group': '그룹 추가',
        'no_groups_yet': '아직 그룹이 없습니다',
        'group_list_load_error': '그룹 목록 로드 실패: {e}',
        'group_name': '그룹 이름',
        'group_created_success': '그룹이 생성되었습니다',
        'group_save_error': '그룹 저장 실패: {e}',
        'manage_all_permissions': '모든 권한 관리',
        'add_permission': '권한 추가',
        'permission_name': '권한 이름',
        'permission_created_success': '권한이 생성되었습니다',
        'permission_save_error': '권한 저장 실패: {e}',
        'confirm_delete_group_title': "그룹 '{name}'을(를) 삭제하시겠습니까?",
        'group_deleted_success': '그룹이 삭제되었습니다',
        'group_delete_error': '그룹 삭제 실패: {e}',
        'confirm_delete_permission_title': "권한 '{name}'을(를) 삭제하시겠습니까?",
        'permission_deleted_success': '권한이 삭제되었습니다',
        'permission_delete_error': '권한 삭제 실패: {e}',
        'select_user_prompt': '왼쪽에서 사용자를 선택하세요',
        'editing_user': '편집 중인 사용자: {username}',
        'group_load_error': '그룹 로드 중 오류 발생: {e}',
        'no_user_selected': '선택된 사용자 없음',
        'user_groups_updated_success': "사용자 '{username}'의 그룹이 성공적으로 업데이트되었습니다.",
        'user_list': '사용자 목록',
        'no_users_yet': '아직 사용자가 없습니다',
        'go_add_user': '사용자 추가로 이동',
        'user_list_load_error': '사용자 목록 로드 실패. 자세한 내용은 로그를 확인하세요.',
        'prompts_saved_success': '프롬프트가 성공적으로 저장되었습니다!',
        'prompt_save_error': '프롬프트 저장 실패: {e}',
        'save_prompts': '프롬프트 저장',
        'prompt_load_error': '프롬프트 로드 실패: {e}',
        'exit_management': '관리 센터 나가기',
        'app_version_trend': '앱 버전 반복 추세',
        'versions_created_per_day': '일일 생성 버전 수',
        'date': '날짜',
        'version_count': '버전 수',
        'published_app_category_distribution': '게시된 앱의 카테고리 분포',
        'category': '카테고리',
        'app_count': '앱 수',
        'no_data_available': '데이터 없음',
        'other_apps': '기타 상태',
        'app_status_distribution': '앱 상태 분포',
        'app_status': '앱 상태',
        'ai_model_management': 'AI 모델 관리',
        'configured_ai_models': '구성된 AI 모델',
        'add_model': '모델 추가',
        'edit_model': '모델 수정',
        'model_name': '모델 이름',
        'technical_model_name': '기술 모델 이름',
        'code_generation_model': '코드 생성',
        'preview_generation_model': '미리보기 생성',
        'report_generation_model': '보고서 생성',
        'ai_model_load_error': 'AI 모델 로드 실패: {e}',
        'model_status_updated_success': '모델 활성화 상태가 업데이트되었습니다.',
        'model_status_update_error': '모델 상태 업데이트 실패: {e}',
        'custom_model_name': '사용자 지정 모델 이름',
        'api_key': 'API 키',
        'endpoint_url': 'API 엔드포인트 URL',
        'model_updated_success': '모델이 성공적으로 업데이트되었습니다.',
        'model_created_success': '모델이 성공적으로 추가되었습니다.',
        'model_save_error': '모델 저장 실패: {e}',
        'confirm_delete_model_title': '이 모델을 삭제하시겠습니까?',
        'deleting_model_info': '삭제할 모델: {name}',
        'model_deleted_success': '모델이 성공적으로 삭제되었습니다.',
        'model_delete_error': '모델 삭제 실패: {e}',
        'general_settings': '일반 설정',
        'status_draft': '초안',
        'status_in_review': '검토 중',
        'status_approved': '승인됨',
        'status_rejected': '거부됨',
        'status_published': '게시됨',
        'status_archived': '보관됨',
        'status_deleted': '삭제됨',
        'require_risk_report_before_approval': '승인 전 위험 탐지 보고서 생성 필요',
        'must_generate_report_to_approve': '승인하려면 먼저 위험 보고서를 생성해야 합니다',
        'generating_report_before_submission': '제출 전 위험 보고서 생성 중...',
        'report_generation_failed_before_submission': '제출 전 보고서 생성 실패: {e}',
        'published_app_management': '게시된 앱 관리',
        'published_at': '게시 시간',
        'unpublish_app': '앱 게시 취소',
        'confirm_unpublish_app_title': '이 앱의 게시를 취소하시겠습니까?',
        'unpublishing_app_info': '게시 취소 대상: {name}',
        'app_unpublished_success_admin': '앱 "{name}"이(가) 성공적으로 게시 취소되었습니다.',
        'unpublish_failed': '게시 취소 실패: {e}',
        'operating_instructions_title': '작동 지침',
        'no_instructions_provided': '작동 지침이 제공되지 않았습니다.',
        'app_functional_description_title': '애플리케이션 설명',
        'language_chinese_traditional': '繁體中文',
        'language_chinese_simplified': '简体中文',
        'language_english': 'English',
        'language_japanese': '日本語',
        'language_korean': '한국어',
        'account_disabled': '계정이 비활성화되었습니다. 관리자에게 문의하십시오.',
        'vibe_slogan': '아이디어에서 애플리케이션까지, 즉시',
        },
   'en': {
        'create_session': 'Creating new session...',
        'version_history': 'Version History',
        'download_application': 'Download application',
        'new_application': 'New Creation',
        'new_app': 'New App',
        'application_filename': 'application-{id}.url',
        'ai_suggestion': 'If the AI result is not as expected, it is recommended to use the button above to return to the previous version and submit the request again.',
        'conversation': 'Conversation',
        'input_placeholder': 'Describe the tool you want...',
        'send': 'Send',
        'stop': 'Stop',
        'tool_preview': 'Tool Preview',
        'edit_code': 'Edit Code',
        'edit_code_manually': 'Edit Code Manually',
        'cancel': 'Cancel',
        'save_changes': 'Save Changes',
        'generate_new_template': 'Generate a new app template for me',
        'chat_you': 'You',
        'chat_ai': 'AI',
        'chat_system': 'System',
        'ai_thinking': 'AI is thinking...',
        'ai_settings_incomplete': 'AI settings are incomplete or incorrect.',
        'go_to_management_for_config': '<br>Please click <a href="/management" style="text-decoration: underline; color: #3B82F6;">here</a> to go to the management center for configuration.',
        'system_prompt_not_found': 'System prompt not found.',
        'ai_no_html': 'AI failed to generate valid HTML content.',
        'api_request_failed': '<b>API request failed</b>',
        'cannot_connect_ai': '<b>Could not connect to AI server</b>',
        'unexpected_error': '<b>An unexpected error occurred</b>:',
        'error_notification': 'An error occurred: {e}',
        'ai_busy_or_no_response': 'AI service is busy or not responding',
        'based_on_v': 'Based on V{v_num}',
        'preview_title': 'Version V{v_num}{base_text}',
        'based_on_v_suffix': ' (based on V{v_num})',
        'code_saved_as_v': 'Code was manually modified and saved as V{v_num}.',
        'generated_v': 'Generated V{v_num} for you.',
        'request_changes_for_v': 'Please submit your changes for Version V{v_num}...',
        'cannot_save_no_base': 'Cannot save. No base version or content is empty.',
        'saving_changes': 'Saving changes...',
        'manual_edit_request': 'Manual Edit',
        'no_history': 'No history.',
        'user_request_history': 'User (request for V{v_num}): {request}',
        'window_title': 'Vibe coding DEMO',
        'lang_button': '中/EN',
        'app_store': 'App Store',
        'publish_app': 'Publish App',
        'manage_publish': 'Manage Publication',
        'publish': 'Submit for Review',
        'unpublish': 'Archive',
        'app_name_label': 'App Name',
        'publish_dialog_title': 'Publish App',
        'app_published_success': 'App "{name}" has been submitted for review successfully!',
        'app_unpublished_success': 'App has been successfully archived.',
        'confirm_cancel_submission_text': 'Are you sure you want to cancel the review submission for the app {name}?',
        'confirm_go_live_text': 'Are you sure you want to publish the approved app {name}?',
        'confirm_unpublish_text': 'Are you sure you want to unpublish and archive the app {name}?',
        'app_updated_success': 'App has been updated to version V{v_num}.',
        'use_app': 'Use App',
        'published_mark': '(Published)',
        'dedicated_page': 'Dedicated Page',
        'app_description_placeholder': 'This is a great application that can help you do many things.',
        'version_not_found': 'The specified application version was not found',
        'share_not_found_or_expired': 'The shared application does not exist or has expired',
        'user_login': 'User Login',
        'username': 'Username',
        'password': 'Password',
        'login': 'Login',
        'logout': 'Logout',
        'login_error': 'Incorrect username or password',
        'account_disabled': 'Account is disabled. Please contact administrator.',
        'vibe_slogan': 'From Idea to Application, Instantly',
        'my_apps': 'My Apps',
        'latest_apps': 'Latest Published Apps',
        'no_apps_in_store': 'There are no applications in the store yet.',
        'no_preview_available': 'No preview available',
        'preview_generation_failed': 'Preview generation failed',
        'generating_preview': 'Generating preview...',
        'manage': 'Manage',
        'you_have_no_apps': 'You do not have any applications yet.',
        'my_shares': 'My Shares',
        'app_name': 'App Name',
        'share_link': 'Share Link',
        'expires_at': 'Expires At',
        'actions': 'Actions',
        'permanent': 'Permanent',
        'share_link_removed': 'Share link has been removed.',
        'remove_share': 'Remove Share',
        'copy_link': 'Copy Link',
        'link_copied': 'Link copied to clipboard!',
        'you_have_no_shares': 'You have no shares.',
        'confirm_delete_app_title': 'Are you sure you want to delete this application? This action cannot be undone.',
        'app_deleted': 'Application has been deleted.',
        'confirm_delete': 'Confirm Delete',
        'close': 'Close',
        'share': 'Share',
        'delete_app': 'Delete App',
        'share_app_version': 'Share App Version',
        '1_day': '1 Day',
        '7_days': '7 Days',
        '1_month': '1 Month',
        'share_duration': 'Share Duration',
        'cannot_generate_share_link': 'Could not generate share link.',
        'generate_link': 'Generate Link',
        'share_link_generated': 'Share link has been generated and copied to clipboard!',
        'processing_request': 'Processing your request, please wait...',
        'under_review': 'Under Review',
        'go_live': 'Go Live',
        'manage_published_version': 'Manage Published Version',
        'preview_generating': 'Generating preview...',
        'managing_review_app': 'Managing App Under Review',
        'app_approved': 'Application Approved',
        'cancel_submission': 'Cancel Submission',
        'submission_cancelled': 'Submission has been cancelled.',
        'app_live_success': 'Application has been successfully published!',
        'app_name_required': 'Please enter an application name',
        'app_description_required': 'Please enter an application description',
        'user_info_error': 'Error: User information not found. Please log in again.',
        'app_submitted_for_review': 'Application submitted for review. A preview will be generated in the background.',
        'publish_failed': 'Publish failed: {e}',
        'manual_edit_by_user': 'User manually modified the code.',
        'welcome_message': 'Welcome! Please start with your first request.',
        'archive_before_delete': 'Please archive the application before deleting it.',
        'preview_worker_started': 'Preview generation background worker has started.',
        'template_generation_failed': 'AI failed to generate a valid preview template.',
        'preview_generation_failed_for_session': 'Failed to generate preview for session {session_id}: {e}',
        'preview_worker_error': 'An error occurred in the preview generation worker: {e}',
        'ai_settings_incomplete_for_preview': 'AI settings are incomplete.',
        'app_template_prompt_not_found': 'Application template prompt not found.',
        'headless_template_generation_failed': 'Headless template generation failed: {e}',
        'risk_analysis_prompt_not_found': 'Risk analysis prompt not found in the database.',
        'no_existing_risks': 'None',
        'json_missing_keys': 'Parsed JSON is missing required keys: {keys}',
        'invalid_json_response': 'AI response was not valid JSON.',
        'headless_risk_report_failed': 'Headless risk report generation failed: {e}',
        'permission_denied': 'Permission Denied',
        'management_center': 'Management Center',
        'management_menu': 'Management Menu',
        'dashboard': 'Dashboard',
        'user_management': 'User Management',
        'app_review': 'App Review',
        'system_settings': 'System Settings',
        'user_group_management': 'User Group Management',
        'permission_management': 'Permission Management',
        'prompt_management': 'Prompt Management',
        'dashboard_load_error': 'Failed to load dashboard data: {e}',
        'active_users': 'Active Users',
        'total_apps': 'Total Apps',
        'pending_apps': 'Pending Apps',
        'published_apps': 'Published Apps',
        'user_id': 'ID',
        'status': 'Status',
        'active': 'Active',
        'inactive': 'Inactive',
        'user_load_error': 'Failed to reload user data: {e}',
        'add_user': 'Add User',
        'required_field': 'Required',
        'email': 'Email',
        'password_placeholder': 'Leave blank to keep current password',
        'save': 'Save',
        'user_updated_success': 'User {username} has been updated successfully',
        'password_required_for_new_user': 'Password is required when creating a new user',
        'user_created_success': 'User {username} has been created successfully',
        'save_failed': 'Save failed: {e}',
        'confirm_delete_user_title': 'Are you sure you want to delete this user?',
        'deleting_user_info': 'About to delete: {username} (ID: {id})',
        'user_deleted': 'User {username} has been deleted',
        'delete_failed': 'Delete failed: {e}',
        'edit_user': 'Edit User',
        'edit': 'Edit',
        'delete': 'Delete',
        'developer': 'Developer',
        'pending_apps_load_error': 'Failed to load pending applications: {e}',
        'review_app': 'Review Application',
        'app_info': 'Application Information',
        'review_actions': 'Review Actions',
        'review_comments': 'Review Comments',
        'risk_report': 'Risk Report',
        'generate_risk_report': 'Generate Risk Report',
        'reject': 'Reject',
        'approve': 'Approve',
        'app_review_decision_success': "Application '{app_name}' has been {decision}",
        'app_approved_text': 'approved',
        'app_rejected_text': 'rejected',
        'review_op_failed': 'Review operation failed: {e}',
        'risk_analysis': 'Risk Analysis',
        'high_risk': 'High',
        'medium_risk': 'Medium',
        'low_risk': 'Low',
        'no_risks_found': 'No risks found.',
        'no_risk_detected': 'No risk detected',
        'suggested_categories': 'Suggested Categories',
        'functional_description': 'Functional Description',
        'operating_instructions': 'Operating Instructions',
        'app_details_not_found': 'Could not find application details',
        'app_missing_submitted_version': 'Application is missing a submitted version',
        'no_description_provided': 'No description provided',
        'submitted_at': 'Submitted At',
        'app_description': 'App Description',
        'regenerate_report': 'Regenerate Report',
        'click_to_generate_report': 'Click the button to generate a report...',
        'review_dialog_open_error': 'Failed to open review dialog: {e}',
        'missing_version_info_for_report': 'Missing version information, cannot generate report',
        'generating_report_in_progress': 'Generating report, please wait...',
        'report_generated_success': 'Report generated successfully',
        'report_generation_error': 'An error occurred while generating the report: {e}',
        'review': 'Review',
        'production_ai_settings': 'Production AI Settings',
        'preview_ai_settings': 'Preview AI Settings',
        'app_publish_settings': 'Application Publish Settings',
        'auto_publish_on_approval': 'Auto-publish on approval',
        'settings_saved_success': 'System settings have been saved successfully!',
        'settings_save_error': 'Failed to save settings: {e}',
        'save_settings': 'Save Settings',
        'settings_load_error': 'Failed to load system settings: {e}',
        'select_group_prompt': 'Please select a group from the left',
        'editing_group': 'Editing group: {name}',
        'no_description': 'No description',
        'manage_permissions': 'Manage Permissions',
        'save_changes_permissions': 'Save Changes',
        'permission_load_error': 'Error loading permissions: {e}',
        'no_group_selected': 'No group selected',
        'group_permissions_updated_success': "Successfully updated permissions for group '{name}'.",
        'group_list': 'Group List',
        'add_group': 'Add Group',
        'no_groups_yet': 'There are no groups yet',
        'group_list_load_error': 'Failed to load group list: {e}',
        'group_name': 'Group Name',
        'group_created_success': 'Group created successfully',
        'group_save_error': 'Failed to save group: {e}',
        'manage_all_permissions': 'Manage All Permissions',
        'add_permission': 'Add Permission',
        'permission_name': 'Permission Name',
        'permission_created_success': 'Permission created successfully',
        'permission_save_error': 'Failed to save permission: {e}',
        'confirm_delete_group_title': "Are you sure you want to delete the group '{name}'?",
        'group_deleted_success': 'Group deleted successfully',
        'group_delete_error': 'Failed to delete group: {e}',
        'confirm_delete_permission_title': "Are you sure you want to delete the permission '{name}'?",
        'permission_deleted_success': 'Permission deleted successfully',
        'permission_delete_error': 'Failed to delete permission: {e}',
        'select_user_prompt': 'Please select a user from the left',
        'editing_user': 'Editing user: {username}',
        'group_load_error': 'Error loading groups: {e}',
        'no_user_selected': 'No user selected',
        'user_groups_updated_success': "Successfully updated groups for user '{username}'.",
        'user_list': 'User List',
        'no_users_yet': 'There are no users yet',
        'go_add_user': 'Go to Add User',
        'user_list_load_error': 'Failed to load user list. Please check logs for details.',
        'prompts_saved_success': 'Prompts have been saved successfully!',
        'prompt_save_error': 'Failed to save prompts: {e}',
        'save_prompts': 'Save Prompts',
        'prompt_load_error': 'Failed to load prompts: {e}',
        'exit_management': 'Exit Management Center',
        'app_version_trend': 'App Version Iteration Trend',
        'versions_created_per_day': 'Versions Created Per Day',
        'date': 'Date',
        'version_count': 'Version Count',
        'published_app_category_distribution': 'Published App Category Distribution',
        'category': 'Category',
        'app_count': 'App Count',
        'no_data_available': 'No data available',
        'other_apps': 'Other Statuses',
        'app_status_distribution': 'App Status Distribution',
        'app_status': 'App Status',
       'ai_model_management': 'AI Model Management',
       'configured_ai_models': 'Configured AI Models',
       'add_model': 'Add Model',
       'edit_model': 'Edit Model',
       'model_name': 'Model Name',
       'technical_model_name': 'Technical Model Name',
       'code_generation_model': 'Code Generation',
       'preview_generation_model': 'Preview Generation',
       'report_generation_model': 'Report Generation',
       'ai_model_load_error': 'Failed to load AI models: {e}',
       'model_status_updated_success': 'Model activation status updated.',
       'model_status_update_error': 'Failed to update model status: {e}',
       'custom_model_name': 'Custom Model Name',
       'api_key': 'API Key',
       'endpoint_url': 'API Endpoint URL',
       'model_updated_success': 'Model updated successfully.',
       'model_created_success': 'Model created successfully.',
       'model_save_error': 'Failed to save model: {e}',
       'confirm_delete_model_title': 'Are you sure you want to delete this model?',
       'deleting_model_info': 'About to delete model: {name}',
       'model_deleted_success': 'Model deleted successfully.',
       'model_delete_error': 'Failed to delete model: {e}',
       'general_settings': 'General Settings',
       'status_draft': 'Draft',
       'status_in_review': 'In Review',
       'status_approved': 'Approved',
       'status_rejected': 'Rejected',
       'status_published': 'Published',
       'status_archived': 'Archived',
       'status_deleted': 'Deleted',
       'require_risk_report_before_approval': 'Require risk report generation before approval',
       'must_generate_report_to_approve': 'A risk report must be generated before approving',
       'published_app_management': 'Published App Management',
       'published_at': 'Published At',
       'unpublish_app': 'Unpublish App',
       'confirm_unpublish_app_title': 'Are you sure you want to unpublish this app?',
       'unpublishing_app_info': 'About to unpublish: {name}',
       'app_unpublished_success_admin': 'App "{name}" has been unpublished successfully.',
       'unpublish_failed': 'Unpublish failed: {e}',
       'operating_instructions_title': 'Operating Instructions',
       'no_instructions_provided': 'No instructions provided.',
       'app_functional_description_title': 'Application Description',
       'language_chinese_traditional': '繁體中文',
       'language_chinese_simplified': '简体中文',
       'language_english': 'English',
       'language_japanese': '日本語',
       'language_korean': '한국어',
        },
        'go_to_management_for_config': '<br>Please click <a href="/management" style="text-decoration: underline; color: #3B82F6;">here</a> to go to the management center for configuration.'
     }

def set_language(lang: str):
    """Sets the language in the user's session and reloads the page."""
    app.storage.user['lang'] = lang
    ui.navigate.reload()

def get_lang() -> str:
    try:
        return app.storage.user.get('lang', 'en')
    except RuntimeError:
        # This can happen when called from a background task that has no user context.
        return 'en' # Fallback to default language

class Translator:
    def __call__(self, key: str, **kwargs) -> str:
        lang = get_lang()
        lang_dict = LANGUAGES.get(lang)
        if not lang_dict:
            return LANGUAGES['en'].get(key, key).format(**kwargs)
        return lang_dict.get(key, LANGUAGES['en'].get(key, key)).format(**kwargs)

    @property
    def lang(self) -> str:
        return get_lang()

T = Translator()